import {
  GREENFIELD_FILE_PATHS,
  type GeneratedFile,
  type GreenfieldFilePath,
} from "@/core/greenfield/types";
import { isRecoverablePartialContent } from "@/core/greenfield/parseResponse";

export const CRITICAL_GREENFIELD_PATHS: readonly GreenfieldFilePath[] = [
  "src/App.tsx",
];

const SKELETON: Record<GreenfieldFilePath, string> = {
  "package.json": JSON.stringify(
    {
      name: "greenfield-app",
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc -p tsconfig.json && vite build",
        typecheck: "tsc -p tsconfig.json --noEmit",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
      },
      devDependencies: {
        "@types/react": "^18.3.3",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^5.0.0",
        typescript: "^5.4.5",
        vite: "^5.3.1",
      },
    },
    null,
    2,
  ),
  "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
  "src/main.tsx": `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);`,
  "src/App.tsx": `export default function App() {
  return (
    <main>
      <h1>New app</h1>
      <p>Generated by BryantLabs Studio.</p>
    </main>
  );
}`,
  "src/index.css": `* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: system-ui, sans-serif;
  background: #0f1419;
  color: #e6edf3;
}

main {
  padding: 2rem;
}`,
  "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src", "vite.config.ts"]
}`,
  "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});`,
};

export function isFallbackSkeletonAppContent(content: string): boolean {
  if (!/export\s+default\s+function\s+App\b/i.test(content)) return false;
  return (
    /<h1>\s*New app\s*<\/h1>/i.test(content) &&
    /<main[\s>]/i.test(content) &&
    !/react-router|BrowserRouter|Routes|Route\s+path=/i.test(content) &&
    !/useState\s*\(\s*["'`]/.test(content)
  );
}

function extractAppTitle(userPrompt: string | undefined): string {
  if (!userPrompt?.trim()) return "App";
  const called = userPrompt.match(/\bcalled\s+([A-Za-z][\w-]*)/i);
  if (called?.[1]) return called[1];
  const named = userPrompt.match(/\bapp\s+([A-Za-z][\w-]*)/i);
  if (named?.[1]) return named[1];
  return "App";
}

function extractPageNames(userPrompt: string | undefined): string[] {
  if (!userPrompt?.trim()) return ["Dashboard", "Settings"];
  const pagesSection = userPrompt.match(/Pages:\s*([\s\S]*?)(?:\n\n|\nRequirements:|\nUse:|\nGoal:)/i);
  const source = pagesSection?.[1] ?? userPrompt;
  const numbered = [...source.matchAll(/^\s*\d+\.\s*([^\n]+)/gm)].map((m) =>
    m[1]!.replace(/\s*[-–—].*$/, "").trim(),
  );
  const cleaned = numbered.filter((name) => name.length > 0 && name.length < 40);
  return cleaned.length > 0 ? cleaned : ["Dashboard", "Settings"];
}

/** Local multi-page shell when provider output truncates before src/App.tsx. Not the generic placeholder skeleton. */
export function buildCriticalAppScaffold(userPrompt?: string): string {
  const title = extractAppTitle(userPrompt);
  const pages = extractPageNames(userPrompt);
  const pageKeys = pages.map((name) =>
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, ""),
  );
  const defaultPage = pageKeys[0] ?? "dashboard";

  const navItems = pages
    .map(
      (name, idx) =>
        `            <li><a href="#" className={page === "${pageKeys[idx]}" ? "active" : undefined} onClick={(event) => { event.preventDefault(); setPage("${pageKeys[idx]}"); }}>${name}</a></li>`,
    )
    .join("\n");

  const pageBlocks = pages
    .map(
      (name, idx) =>
        `      {page === "${pageKeys[idx]}" ? (
        <section className="page-content">
          <div className="page-header">
            <h1>${name}</h1>
          </div>
          <div className="card">
            <p className="card-header">${title} — ${name}</p>
            <p>Content for ${name.toLowerCase()} will load here. Data persists via localStorage in a follow-up pass.</p>
          </div>
        </section>
      ) : null}`,
    )
    .join("\n");

  return `import { useEffect, useState } from "react";

type Page = ${pageKeys.map((k) => `"${k}"`).join(" | ")};

export default function App() {
  const [page, setPage] = useState<Page>("${defaultPage}");
  const [sidebarOpen, setSidebarOpen] = useState(false);

  useEffect(() => {
    document.title = "${title}";
  }, []);

  return (
    <div className="app-layout">
      <aside className={sidebarOpen ? "sidebar open" : "sidebar"}>
        <div className="sidebar-header">${title}</div>
        <nav className="sidebar-nav">
          <ul>
${navItems}
          </ul>
        </nav>
      </aside>
      <div className="main-content">
        <header className="header">
          <button type="button" className="mobile-menu-button" onClick={() => setSidebarOpen((v) => !v)} aria-label="Menu">
            ☰
          </button>
          <div className="search-bar">
            <input className="search-input" placeholder="Search ${title}…" />
          </div>
        </header>
${pageBlocks}
      </div>
    </div>
  );
}`;
}

export function buildGreenfieldFallbackSkeleton(
  userPrompt?: string,
): GeneratedFile[] {
  const appHint = userPrompt?.trim().slice(0, 120);
  return GREENFIELD_FILE_PATHS.map((path) => ({
    path,
    content:
      path === "src/App.tsx" && appHint
        ? `export default function App() {
  return (
    <main>
      <h1>New app</h1>
      <p>${appHint.replace(/`/g, "'")}</p>
    </main>
  );
}`
        : SKELETON[path],
  }));
}

export interface FillMissingGreenfieldResult {
  readonly files: GeneratedFile[];
  readonly skeletonFilledPaths: readonly GreenfieldFilePath[];
  readonly appShellIncomplete: boolean;
  readonly recoveredPartialPaths: readonly GreenfieldFilePath[];
}

export function fillMissingGreenfieldFiles(
  existing: readonly GeneratedFile[],
  missing: readonly GreenfieldFilePath[],
  userPrompt?: string,
  options?: {
    readonly recoveredPartials?: Readonly<Partial<Record<GreenfieldFilePath, string>>>;
    readonly allowCriticalSkeleton?: boolean;
  },
): FillMissingGreenfieldResult {
  const skeleton = buildGreenfieldFallbackSkeleton(userPrompt);
  const skeletonMap = new Map(skeleton.map((f) => [f.path, f.content]));
  const merged = new Map<GreenfieldFilePath, string>();
  for (const file of existing) merged.set(file.path, file.content);

  const pathsToFill = [
    ...new Set([
      ...missing,
      ...GREENFIELD_FILE_PATHS.filter((path) => !merged.has(path) || !merged.get(path)!.trim()),
    ]),
  ] as GreenfieldFilePath[];

  const skeletonFilledPaths: GreenfieldFilePath[] = [];
  const recoveredPartialPaths: GreenfieldFilePath[] = [];
  let appShellIncomplete = false;

  for (const path of pathsToFill) {
    if (merged.has(path) && merged.get(path)!.trim()) continue;

    const recovered = options?.recoveredPartials?.[path]?.trim();
    if (recovered && isRecoverablePartialContent(path, recovered)) {
      merged.set(path, recovered);
      recoveredPartialPaths.push(path);
      continue;
    }

    const isCritical = CRITICAL_GREENFIELD_PATHS.includes(path);
    if (isCritical && !options?.allowCriticalSkeleton) {
      appShellIncomplete = true;
      continue;
    }

    merged.set(path, skeletonMap.get(path) ?? "");
    skeletonFilledPaths.push(path);
    if (path === "src/App.tsx") {
      appShellIncomplete = true;
    }
  }

  const files = GREENFIELD_FILE_PATHS.filter((p) => merged.has(p)).map((path) => ({
    path,
    content: merged.get(path)!,
  }));

  return {
    files,
    skeletonFilledPaths,
    appShellIncomplete,
    recoveredPartialPaths,
  };
}
